/*
	DESCRIPTION:
	Hangman game is a classic pencil-and-paper word guessing game, there are now electronic version.
	It is typically played by single or two players, one of whom thinks of a word and the other tries to guess it by suggesting letters. 
	The word is represented by a series of asterisks, one for each letter, and the guessing player tries to guess the word by suggesting letters 
	that they think are in the word. 
	For each incorrect guess, a part of a stick figure is drawn, typically starting with a head and moving down to the body, arms, legs, and finally a hanging rope. 
	The goal is to correctly guess the word before the stick figure is fully drawn, in which case the player loses the game. 
	Hangman can be used to improve vocabulary and spelling skills, as well as for pure entertainment.
	
	To play the game, follow these steps:

	Run the program and the welcome banner will be displayed.
	Select option 1 from the menu to play the game.
	There are two options, single player and multiplayer.
	If you choose singleplayer, the word will be generated by the computer.
	If you choose multiplayer, player 1 will enter the word to be guessed by player 2
	To view the instructions on how to play this game, select option 2 from the menu. 
	To exit the program, select option 3 from the menu.
*/

/*
	In this section nag include ako ng 5 header files. These header files provide functions and macros to perform 
	standard input/output operations, memory allocation and conversion of data, string manipulation, time manipulation, 
	and character testing and conversion. 
*/
#include <stdio.h> 
#include <stdlib.h> 
#include <string.h> 
#include <time.h> 
#include <ctype.h> 

/* 
	In this section, I used three constants, MAX_WORD_LENGTH, MAX_NAME_LENGTH, and MAX_GUESSES, and an array of strings 
	called WORDS. 
	I set the value of the constant integer variable MAX_WORD_LENGTH to 50. This value represents 
	the maximum length of a word that can be stored in the "WORDS" array.
	I set the value of the constant integer variable MAX_NAME_LENGTH to 20. This value represents 
	the maximum length of a name of a player or any string data that is being stored.
	I set the value of tthe constant integer variable MAX_GUESSES to 6. This value represents the 
	maximum number of attempts or guesses a player can make.
	The "const char* WORDDS[] is an array of strings na nag contain ng 16 string elements, 
	and each string represents a word na i guess ng player, I used "const" to make the "WORDS" a  
	constant array of a strings, meaning its contents cannot be modified, and the "*" there is a 
	pointer.
*/
const int MAX_WORD_LENGTH = 50; 
const int MAX_NAME_LENGTH = 20;
const int MAX_GUESSES = 6; 
const char* WORDS[] = {"bit", "bug", "cpu", "cpe", "net", "ram",  
                       "binary", "hacker", "laptop", "memory", "reboot", "server", 
	                	"algorithm", "flowchart", "interface", "iterative"}; 

/*
	I created my own functions that can be call later in the main function.
*/

/*
	In this function, the "printf" will display the text
	"WELCOME TO HANGMAN" on the screen, in the main menu of the game.
*/
void printWelcomeBanner() { 
    printf("WELCOME TO HANGMAN\n");
}

/* 
 	In this function, it displays a menu with three options.
*/
void printMenu() { 
    printf("1. Play\n");
    printf("2. Instructions\n");
    printf("3. Exit\n");
}

/*
	In this function, it will get the choice na pinili ng player sa function na 
	"printMenu" and stores sa variable na "choice".
*/
int getMenuChoice() { 
    int choice;
    scanf("%d", &choice);
    return choice;
}

/*
	In this function, everytime ma wrong ang player sa pag guess, it will display the part of
	the hangman.
*/
void drawHangman(int numGuesses) { 
    if (numGuesses == 1) {
        printf("   _______\n");
        printf("   |/    |\n");
        printf("   |\n");
        printf("   |\n");
        printf("   |\n");
        printf("   |\n");
        printf("   |\n");
        printf("___|___\n");
        printf("Wrong Letter!\n");
    }else if (numGuesses == 2){
    	printf("   _______\n");
        printf("   |/    |\n");
        printf("   |     O\n");
        printf("   |     |\n");
        printf("   |\n");
        printf("   |\n");
        printf("   |\n");
        printf("___|___\n");
		printf("Wrong Letter!\n");	
	}else if (numGuesses == 3){
		printf("   _______\n");
        printf("   |/    |\n");
        printf("   |     O\n");
        printf("   |     |\n");
        printf("   |     |\n");
        printf("   |\n");
        printf("   |\n");
        printf("___|___\n");
        printf("Wrong Letter!\n");
	}else if (numGuesses == 4){
		printf("   _______\n");
        printf("   |/    |\n");
        printf("   |     O\n");
        printf("   |    /|\\\n");
        printf("   |     |\n");
        printf("   |\n");
        printf("   |\n");
        printf("___|___\n");
        printf("Wrong Letter!\n");
	}else if (numGuesses == 5){
		printf("   _______\n");
        printf("   |/    |\n");
        printf("   |     O\n");
        printf("   |    /|\\\n");
        printf("   |     |\n");
        printf("   |    / \\\n");
        printf("   |\n");
        printf("___|___\n");
        printf("Wrong Letter!\n");
	}else if (numGuesses == 6){
		printf("   _______\n");
        printf("   |/    |\n");
        printf("   |     X\n");
        printf("   |    /|\\\n");
        printf("   |     |\n");
        printf("   |    / \\\n");
        printf("   |\n");
        printf("___|___\n");
	}
}


void singlePlayer() {
	/*
		 In this section, it takes the user's name, and stores it in an array, and then prints a welcome message 
		 to the user using that input.
	*/
	char name[MAX_NAME_LENGTH];
    printf("Enter your name: ");
    scanf("%s", name);
    printf("Welcome, %s!\n", name);
 	
 	/*
 		wordToGuess: an array to store the word that the player needs to guess
		wordLength: the length of the word that the player needs to guess
		wordIndex: a random index to select the word to be guessed from the WORDS array
		numGuesses: the number of incorrect guesses made by the player
		correctGuesses: the number of correct guesses made by the player
		guessedLetters: an array to store the letters that have been guessed by the player
		numGuessedLetters: the number of letters that have been guessed by the player
		gameWon: a flag that indicates if the player has won the game
		score: a variable that stores the score of the player
	*/ 
	char wordToGuess[MAX_WORD_LENGTH];
    int wordLength;
    int wordIndex;
    int numGuesses = 0;
    int correctGuesses = 0;
    char guessedLetters[26];
    int numGuessedLetters = 0;
    int gameWon = 0;
    int score;
	
	/*
		The "srand" and "rand" functions will generate a random number that is used as the wordIndex.
		The function "time(NULL)" returns the number of seconds elapsed. This value is used as a seed for the 
		srand function, which initializes the random number generator. By seeding the random number generator 
		with "time(NULL)", each time the game is run, a different sequence of random numbers will be generated, 
		which ensures that the word to be guessed is different each time.
		"strcpy" function is used to copy the word at the selected index from WORDS array to wordToGuess. 
		"strlen" function is used to get the length of the word to be guessed.
	*/
	srand(time(NULL)); "srand(time(NULL))"; 
    wordIndex = rand() % (sizeof(WORDS) / sizeof(const char*)); 
    strcpy(wordToGuess, WORDS[wordIndex]);
    wordLength = strlen(wordToGuess);
	
	/*
		In this section here, the letters of the word will replace with asterisks to represent each letter.
	*/
	char hiddenWord[wordLength];
    for (int i = 0; i < wordLength; i++) {
        hiddenWord[i] = '*'; 
    }
    
    /*
    	This code repeatedly runs until either the maximum number of guesses (MAX_GUESSES) is reached or the 
		player correctly guesses all the letters in the word to be guessed (wordToGuess).
		On each iteration, it prompts the player to guess a letter and takes in their input.
    */
	while (numGuesses < MAX_GUESSES && !gameWon) {
		char letter[2];
        printf("Guess a letter %s: ", hiddenWord);
        scanf("%s", letter);
		
		/*
			This code will check if the letter the player has entered has already been guessed by the player.
			
		*/
        int alreadyGuessed = 0;
        for (int i = 0; i < numGuessedLetters; i++) {
            if (letter[0] == guessedLetters[i]) {
                alreadyGuessed = 1;
                break;
            }
        }
		
		/*
			If it hasn't been guessed, it adds the letter to the array "guessedLetters" and increments 
			the "numGuessedLetters".
		*/
        if (!alreadyGuessed) {
            guessedLetters[numGuessedLetters] = letter[0];
            numGuessedLetters++;
			
			/*
				This code checks if the letter entered is present in the word to be guessed. 
				If it is present, it replaces the asterisks in the "hiddenWord" array with the correct letter, 
				increments the "correctGuesses" counter, and prints "Good Guessed!" to the screen.
				I also created a code that will check if there is similar letter so that it will just print the 
				text "Good Guessed!" once.
			*/
			int similarLetter = 0;
            int correctGuess = 0;
            for (int i = 0; i < wordLength; i++) {
                if (wordToGuess[i] == letter[0]) {
                    hiddenWord[i] = letter[0];
                    correctGuess = 1;
                    correctGuesses++;
                }
                else if(hiddenWord[i] == letter[0]+1 || hiddenWord[i] == letter[0]-1){
                	similarLetter = 1;
				}
            }
            if(correctGuess){
            	printf("Good Guessed!\n");
			}
			else if(similarLetter){
				printf("Good Guessed!\n");
			}
			
			/*
				if the letter is incorrect, it will call the function "drawHangman(numGuesses)" with the updated number 
				of guesses to print the part of the hangman
			*/
            if (!correctGuess) {
                numGuesses++;
                drawHangman(numGuesses);
            }
            printf("You have %d chances left\n", MAX_GUESSES - numGuesses);
        } else {
            printf("You already guessed that letter.\n");
        }
		
		/*
			It will check if all the letters in the word to be guessed have been correctly guessed, if so,
			the gameWon flag is set to 1 and the loop terminates.
		*/
        if (correctGuesses == wordLength) {
            gameWon = 1;
        }
    }
	
	/*
		This code will determine if the player win the game or not, if the player win, it prints "Congratulations ...",
		and the score will be calculated and display on the screen, if the player lose, it prints "Sorry... you lost...",
		and the score will be calculated and display on the screen.
	*/
    if (gameWon) { 
        printf("Congratulations! %s. You won the game. The word was \"%s\".\n", name, wordToGuess); 
    	score = correctGuesses - numGuesses; 
    	printf("Your score is: %d\n", score);
	} else { 
    	printf("Sorry %s, you lost. The word was \"%s\".\n", name, wordToGuess);
    	score = correctGuesses - numGuesses; 
    	printf("Your score is: %d\n", score);
	}
}


void multiplayer() { 
	/*
		The code prompts the player 1 and player 2 to enter their names and greets them. 
		Then it asks player 1 to enter a word for player 2 to guess. The word entered by player 1 is validated to check if it contains any uppercase letters or numbers, and if so, the player is prompted again to enter a word until a valid word is entered.
	*/
    char player1Name[MAX_NAME_LENGTH]; 
    char player2Name[MAX_NAME_LENGTH]; 
    printf("Player 1, enter your name: ");
    scanf("%s", &player1Name);
	printf("Player 2, enter your name: ");
    scanf("%s", &player2Name);

    printf("Welcome, %s and %s!\n", player1Name, player2Name);
    
    /*
    	This code will ask player 1 to input a word for player 2 to guess. It validates the input word by 
		checking if it contains any capital letters or numbers, and if so, it prints an error message. 
		The loop continues until a valid word is entered. The length of the word is stored in wordLength for later use.
		The purpose of the code is to enforce the rule that only lowercase letters are 
		allowed in the word to be guessed in the game.
    */
    char word[MAX_WORD_LENGTH];
    int wordLength;
    while (1) {
        printf("%s, please enter a word for %s to guess: ", player1Name, player2Name);           
        scanf("%s", word);
        wordLength = strlen(word); 
        int flag = 0; 
        for(int i = 0; i < wordLength; i++) { 
            if(isupper(word[i])) { 
                printf("Capital letters are not allowed!\n");
                flag = 1;
                break;
            }else if(isdigit(word[i])){ 
            	printf("Numbers are not allowed!\n");
                flag = 1;
                break;
			}
        }
        if(!flag) break; 
    }
    
	/*
    	This code will clear the terminal screen, so player 2 will not see the word that was entered by player 1. 
		This helps to maintain the secrecy of the word and make the guessing game more challenging for player 2.
    */
    system("cls"); 
    
    /*
    	These variables are used to keep track of the progress of the game and determine whether the player has won or lost.
    */
    int chances = 6;
    char guesses[26] = {0};
    int numGuesses = 0;
    int correctGuesses = 0;
    char hiddenWord[MAX_WORD_LENGTH];
    
    /*
    	This loop runs from 0 to "wordLength" and sets each element of the "hiddenWord" array to the character '*'. 
		This is to conceal the word from the player and display a representation of the hidden word as asterisks.
		the null character '\0' makes "hiddenWord" a null-terminated string
    */
	for(int i = 0; i < wordLength; i++) {
        hiddenWord[i] = '*';
    }
    hiddenWord[wordLength] = '\0';
    
    /*
    	This lopp runs until the number of guesses made by the player reaches the maximum allowed guesses "(MAX_GUESSES)". 
		In each iteration of the loop, the player will be asked to enter a single letter as their guess.
    */
    while (numGuesses < MAX_GUESSES) {
    	char letter[2];
    	printf("You have %d chances left.\n", chances - numGuesses);
        printf("%s, guess a letter %s:  ", player2Name, hiddenWord);
        scanf(" %c", &letter);
       
	    /*
        	This code check if the player has already guessed the same letter, if so then they are notified and 
			the loop continues. If the player's guess is a new letter, it is added to the "guesses" array.
        */
        if (guesses[letter[0] - 'a'] || letter[0] == ' ') {
            printf("You already guessed that letter. Try again.\n");
            continue;
        }
        guesses[letter[0] - 'a'] = 1;
        
        /*
        	This code checks if the letter that the player guessed matches a letter in the hidden word.
        	If the letter matches a letter in the hidden word, it updates the hidden word with the correct letter and 
			increases the correctGuesses counter.
        */
		int similarLetter = 0;
		int correctGuess = 0;
		int found = 0;
        for (int i = 0; i < wordLength; i++) {
            if (word[i] == letter[0]) {
                found = 1;
                hiddenWord[i] = letter[0];
                correctGuesses++;
                correctGuess = 1;
            }
            else if(hiddenWord[i] == letter[0]+1 || hiddenWord[i] == letter[0]-1){
                	similarLetter = 1;
				}
        }
        if(correctGuess){
        	printf("Good Guessed!\n");
		}
		else if(similarLetter = 1){
			printf("Good Guessed!\n");
		}
		
		/*
			This code checks if the guessed letter is not found in the word, increments the number of guesses made, 
			and calls the "drawHangman" function with the updated number of guesses. 
		*/
		if (!found) {
            numGuesses++;
            drawHangman(numGuesses);
        }
        
        /*
        	This code calculates the score.
			If the number of correct guesses is equal to the length of the word, it displays a message indicating that 
			player 2 wins the game and shows their score. 
			If the number of guesses made is equal to the maximum number of allowed guesses, it displays a message 
			indicating that player 2 loses the game and displays the word and player 1's score.
        */
        int score = correctGuesses - numGuesses;
        if (correctGuesses == wordLength) {
            printf("%s, You win the game!\n", player2Name);
            printf("Your score is %d\n", score);
            break;
        } 
        else if (numGuesses == MAX_GUESSES) {
            printf("%s, You lose the game. The word was \"%s\".\n", player2Name, word);
            printf("%s, You win the game!\n", player1Name);
            printf("%s's score is %d\n", player2Name, score);
        }
    }
}

/*
	This code prints the instruction on how to play the game, and the option 1 to exit from instruction.
*/
void Instructions() {
	printf("Welcome to Hangman! A guessing game where the player tries to guess a word by suggesting letters, within a certain number of guesses.\n");
	printf("In this version of Hangman, player can play in single player or multiplayer mode.\n");
	printf("In single player mode,the computer will randomly choose a word for player to guess.\n");
	printf("The player can make up to 6 incorrect guesses before losing the game.\n");
	printf("In multiplayer mode, choose one person to be the \"host\".\n"); 
	printf("They will be tasked with entering a word that the other \"player\" will have to solve.\n");
	printf("The host should be able to spell confidently or the game will be impossible to win.\n");
	printf("The player can make up to 6 incorrect guesses before losing the game.\n");
	printf("Please note, the host is not allowed to enter a word with capital letters or numbers.\n");
	printf("The player can only guess one letter at a time.\n");
	printf("The player can't repeat the guess letter.\n");
	printf("If the player correctly guesses all letters in the word, they win the game.\n");
	int choice;
	printf("1.Back\n");
	scanf("%d", &choice);
	
	/*
		This code prints the error message until the player selected "1"
	*/
	while(choice!=1){
		printf("Invalid choice, please try again\n");
		printf("1.Back\n");
		scanf("%d", &choice);
	}
	system("cls");
	return;	
} 

/*
	This code provides the player with options to play the game as single player or multiplayer, or return back 
	to the main menu. The player's choice is captured through a switch statement and corresponding functions are 
	called depending on the player's choice. If the choice is not valid, the function will print 
	"Invalid choice, please try again" and call the function play again.
*/
void play(){
    int choice;
    printf("1. Single Player\n");
    printf("2. Multiplayer\n");
    printf("3. Back\n");
    scanf("%d", &choice);
    switch(choice){
        case 1:
        	system("cls");
            singlePlayer();
            break;
        case 2:
        	system("cls");
        	multiplayer();
            break;
        case 3:
        	system("cls");
            return;
            break;
        default:
            printf("Invalid choice, please try again\n");
            play();
            break;
    }
    
}

/*
	These "#define" statements in the code are defining two constants false and true with the values of 0 and 1 
	respectively.
*/	
#define false 0
#define true 1

/*
	This code is the main function of the program and it implements a menu-based user interface. 
	The menu allows the user to choose from three options to play the game, to display the instruction, or to exit the program.
	The menu is displayed in a loop, until the user selects the "Exit" option. 
	The printWelcomeBanner and printMenu functions display the welcome message and the menu, respectively. 
	The getMenuChoice function retrieves the user's choice. 
	The player's choice is captured through a switch statement and corresponding functions are 
	called depending on the player's choice. If the choice is not valid, the function will print 
	"Invalid choice, please try again" and call the function play again.
*/
int main() {
    int choice;
    int running = true;   
    printWelcomeBanner();
    while (running) {
        printMenu();
        choice = getMenuChoice();
        switch (choice) {
            case 1:
            	system("cls");
                play();
                break;
            case 2:
            	system("cls");
      		    Instructions();
                break;
            case 3:
                running = false;
                printf("Exiting...");
                break;
            default:
                printf("Invalid choice, please try again\n");
                break;
        }
    }
    return 0;
}

/*
	SA WAKAS MATAPOS ANG ALMOST 24 HOURS NA CODING AND TRIAL AND ERROR NATAPOS DIN. HEHEHE :)
*/